name: BUN CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bun-version: [1.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Bun.js v${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v1
        with:
          version: ${{ matrix.bun-version }}
      - run: bun install
      - run: bun run build
      - run: bun run lint
      - run: bun run test:ci
